Add the type information and comments to functions
Countly/countly-sdk-react-native-bridge pull request #274
Opened 2023-12-04 09:53 UTC by peterBrxwn

2023-12-04 09:54 UTC, peterBrxwn commented
![](https://github.trello.services/images/mini-trello-icon.png) [[RN] Add the type information and comments to functions](https://trello.com/c/TBjop3qT/881-rn-add-the-type-information-and-comments-to-functions)

2023-12-04 09:57 UTC, turtledreams commented
Run linter here. Remove comments. Remove the import at top.

2023-12-05 10:09 UTC, turtledreams requested changes

2023-12-05 10:09 UTC, turtledreams commented on Countly.d.ts
> +  type ResultObject = (
I checked this at the example we have and it was giving an error. Changing it to this fixed it:
  type ResultObject = {
    error: string,
    data: object,
  };
So can you go through the example app and check the errors coming through and fix them.

2023-12-05 13:26 UTC, peterBrxwn commented on Countly.d.ts
> +// export function recordNetworkTrace(data: NetworkTraceData): void;
yup... fixed

2023-12-12 08:47 UTC, turtledreams requested changes
move types outside of declaration

2023-12-12 08:47 UTC, turtledreams commented
dmed u an image

2023-12-13 05:51 UTC, ijunaid approved these changes
Overall, it looks good to me. Please make sure on your side that it's working fine with typescript apps, and if we have an example app/file for typescript, that would be more helpful.

2023-12-13 05:51 UTC, ijunaid commented on Countly.d.ts
@peterBrxwn, have you tested it? 
Do we have an example file/app for typescript to check that it's working fine?

2023-12-13 09:24 UTC, turtledreams requested changes

2023-12-13 09:24 UTC, turtledreams commented on Countly.d.ts
> +    export function endEvent(options: CountlyEventOptions): string | void;
this can also take string

2023-12-13 12:03 UTC, merged