Added all function comments
Countly/countly-sdk-react-native-bridge pull request #298
Opened 2024-01-24 21:34 UTC by peterBrxwn

2024-01-25 07:06 UTC, arifBurakDemiray commented on Countly.d.ts
> +     * @param {[string]} keyNames array of keys to replace.
array docs like that? is not it "string[]"

2024-01-25 07:08 UTC, arifBurakDemiray commented on Countly.js
>  Countly.endTrace = function (traceKey, customMetric) {
what about other param?

2024-01-25 07:11 UTC, arifBurakDemiray requested changes
I do not think return doc required for the only void ones

2024-01-25 11:02 UTC, peterBrxwn commented
![](https://github.trello.services/images/mini-trello-icon.png) [[RN] Add missing "return value" comments and missing function comments in general](https://trello.com/c/1zFAw6bX/1367-rn-add-missing-return-value-comments-and-missing-function-comments-in-general)

2024-01-26 12:06 UTC, arifBurakDemiray approved these changes

2024-02-01 09:17 UTC, turtledreams approved these changes

2024-02-01 11:15 UTC, merged