Staging np
Countly/countly-sdk-react-native-bridge pull request #366
Opened 2024-07-03 13:52 UTC by peterBrxwn

2024-07-03 13:57 UTC, peterBrxwn commented
![](https://github.trello.services/images/mini-trello-icon.png) [[RN] Create NP version](https://trello.com/c/CjLqASqQ/1883-rn-create-np-version)

2024-07-05 06:08 UTC, turtledreams requested changes
well looks like there are some checks we should talk about. call me

2024-07-08 06:38 UTC, turtledreams requested changes
there are push related methods you have not touched yet.
there are return types and comments that should be looked at.
this should be a drop in replacement => in the example use the methods we manipulate here so we are sure they wont break when used with np.

2024-07-18 07:08 UTC, ijunaid commented on android/src/main/java/ly/count/android/sdk/react/CountlyReactNative.java
> +            log("askForNotificationPermission, firebaseMessagingInstance is null", LogLevel.WARNING);
It look like that try block is of now use. we can remove it?

2024-07-18 07:12 UTC, arifBurakDemiray commented on android/src/main/java/ly/count/android/sdk/react/CountlyReactNative.java
> -            FirebaseApp.initializeApp(context);
we can directly remove this ReactMethod I think

2024-07-18 07:13 UTC, arifBurakDemiray requested changes
We can remove all push related calls on the android part I think. However, I am not sure it will be ok

2024-07-18 07:14 UTC, ijunaid approved these changes

2024-07-18 07:21 UTC, ijunaid requested changes

2024-07-18 07:21 UTC, ijunaid commented on android/src/main/java/ly/count/android/sdk/react/CountlyReactNative.java
> +            log("askForNotificationPermission, firebaseMessagingInstance is null", LogLevel.WARNING);
It look like that try/catch block is of now use. we can remove it?

2024-07-18 07:52 UTC, arifBurakDemiray approved these changes

2024-07-23 09:16 UTC, ijunaid approved these changes

2024-07-23 13:10 UTC, turtledreams approved these changes

2024-07-23 13:11 UTC, merged